research_task:
  description: >
    Gather and analyze the latest opinions of well-known stock analysts regarding {company}'s stock. Provide a summary of recent news and any notable opinions. Only collect data from freely accessible websites.
  expected_output: >
    Your final answer MUST be a detailed summary of the opinions and news from stock analysts regarding the stock.
  agent: researcher

technical_analyst_task:
  description: >
    Conduct a technical analysis of {company}'s stock price movements. Identify key support and resistance levels as well as any relevant chart patterns.
  expected_output: >
    Your final answer MUST be a report including potential entry points, price targets, and any other relevant technical indicators.
  agent: technical_analyst

financial_analyst_task:
  description: >
    Analyze {company}'s financial statements, balance sheet, insider trading data, and other key metrics to evaluate its financial health and performance.
  expected_output: >
    Your final answer MUST be a report with an overview of {company}'s revenue, earnings, cash flow, and other important financial indicators.
  agent: financial_analyst

hedge_fund_manager_task:
  description: >
    Based on the research, technical analysis, and financial analysis reports, provide a detailed investment recommendation for {company}'s stock.
  expected_output: >
    Your final answer MUST be a detailed recommendation to BUY, SELL, or HOLD the stock, along with a clear rationale supporting your decision.
  agent: hedge_fund_manager
