research_task:
  description: >
    Gather and analyze the latest information regarding {company}. Provide a summary of recent news and any notable opinions. Only collect data from freely accessible websites.
  expected_output: >
    Your final answer MUST be a detailed summary of the opinions and news from stock analysts regarding the stock.
  agent: researcher

technical_analysis_task:
  description: >
    Conduct a technical analysis of {company}'s stock price movements. Identify key support and resistance levels as well as any relevant chart patterns.
  expected_output: >
    Your final answer MUST be a report including potential entry points, price targets, and any other relevant technical indicators.
  agent: technical_analyst

financial_analysis_task:
  description: >
    Analyze {company}'s financial statements, balance sheet, insider trading data, and other key metrics to evaluate its financial health, operating profit margin two years from now, and expected performance.
  expected_output: >
    Your final answer MUST be in the form of a report that includes an overview of {company}'s revenue, earnings, cash flow, and other key financial indicators. It must also include the projected operating profit margin.
  agent: financial_analyst

sentiment_analysis_task:
  description: >
    Analyze {company}'s expert opinions and public sentiment to evaluate how positively company is perceived and how much attention a specific stock is receiving. 
    This includes gathering insights from analysts, social media, forums, and news, assessing the stock’s popularity, and predicting when it might gain significant public interest.
  expected_output: >
    A comprehensive summary report forecasting when and how much attention of {company} is likely to receive in the future.
    The report should include key insights, sentiment trends, popularity indicators, investment-relevant conclusions, and public sentiment.
  agent: sentiment_analyst

stock_decision_task:
  description: >
    Based on the research, technical analysis, sentiment analysis, and financial analysis reports, provide a detailed investment recommendation for {company}'s stock.
  expected_output: >
    Your final answer MUST be a detailed recommendation to BUY, SELL, or HOLD the stock, along with a clear rationale supporting your decision.
  agent: fund_manager
